name: pathChecker
on: 
  workflow_dispatch:

jobs:
  pathChecker:
    runs-on: ubuntu-22.04
    
    steps:
    - name: checkout
      uses: actions/checkout@main
      run: PWD
      run: ll -a $PWD

    - name: checkONE
      run: |
        echo $PWD
        mkdir -p /demo
        sudo chown $USER:$GROUPS /demo

    - name: checkTWO
      working-directory: /workdir
      run: echo $PWD
      
    - name: checkThree
      run: echo $PWD
