name: pathChecker
on:
  workflow_dispatch:

jobs:
  pathChecker:
    runs-on: ubuntu-22.04
    
    steps:
    - name: checkout
      uses: actions/checkout@main

    - name: downloadfile 
      run: |
       ls -a $PWD
       pwd

    - name: checkONE
      run: |
        echo $PWD
        pwd
        sudo mkdir -p /demo
        sudo chown $USER:$GROUPS /demo

    - name: checkTWO
      working-directory: /demo
      run: |
       echo $PWD
       pwd

      
    - name: checkThree
      run: echo $PWD

    - name: creatfile
      run: | 
      echo "hello work" > tar.txt
      echo $PWD

    - name: last
      run: |
      sudo mkdir -p /mnt/workdir
      sudo chown $USER:$GROUPS /mnt/workdir
      ln -sf $GITHUB_WORKSPACE /mnt/workdir
      ls -a $PWD

